### ISSUE TITLE
Petfinder Api Doesn't Fetch Data

### ISSUE THREAD

**Issue by curavcy** [junipdewan/pet#3]
I created .env file on root. I added 
`REACT_APP_API_KEY: = 
REACT_APP_API_SECRET = `

requested from Petfinder Developer account. 

I got this issue 
`<?xml version="1.0" encoding="iso-8859-1"?>

<petfinder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://api.petfinder.com/schemas/0.9/petfinder.xsd">
 <header>
  <version>0.1</version>
  <timestamp>2020-03-28T07:21:21Z</timestamp>
  <status>
   <code>300</code>
   <message>unauthorized key</message>
  </status>
 </header>
</petfinder>

`

**Comment by junipdewan** [comment]
@curavcy Currently, the package Petfinder-client only supports the V1 APIs. So it's not working as expected.For now I have added the [fem-package](https://www.npmjs.com/package/@frontendmasters/pet) & removed the petfinder-client package. APP secret is no longer needed. it will work automatically. For now, you can view the changes.

I need to work on the new API V2 changes & UI changes also.

**Comment by junipdewan** [comment]
@curavcy  Closing this issue, I have redesigned the UI and changed/moved a few packages.Try again with the new changes, API should work.
